docs_dir:           "docs/"

repo_name:          "AoE2DE_UGC_Guide"
repo_url:           "https://github.com/Divy1211/AoE2DE_UGC_Guide"

site_author:        "Alian713, MrKirby, hszemi, Syser"
site_description:   "The Ultimate Guide To AoE2DE UGC"
site_name:          "AoE2DE UGC Guide"
site_url:           "https://ugc.aoe2.rocks"
edit_uri:           "edit/main/docs/"

use_directory_urls: true

nav:
  -                                 "about.md"
  - Game Mechanics:
    -                               "general/index.md"
    - Damage Calculation:           "general/damage_calculation.md"
    -                               "general/attributes/index.md"
    -                               "general/resources/index.md"
    -                               "general/hotkeys/index.md"
  - Custom Scenarios:
    -                               "scenarios/index.md"
    - Triggers:
      -                             "scenarios/triggers/index.md"
      - Effects:                    "scenarios/triggers/effects/effects.md"
    #   - Conditions:               "scenarios/triggers/conditions/conditions.md"
    #   - Variables:                "scenarios/triggers/variables.md"
    # - Tricks and Tips:            "scenarios/tricks.md"
    # - Advanced:
    #   - File Byte Structure:      "scenarios/advanced/byte_structure.md"
    - Useful Tools:
      # - Advanced Genie Editor:
      #   - A.G.E. Uses:            "scenarios/useful_tools/age/uses.md"
      #   - Unhiding Editor Units:  "scenarios/useful_tools/age/unhide.md"
      - AoE2ScenarioParser:
        -                           "scenarios/useful_tools/parser/index.md"
  - XS Scripting:
    -                               "xs/index.md"
    - For Beginners:                "xs/beginner.md"
    - For Programmers:              "xs/programmer.md"
    - Tricks:                       "xs/tricks.md"
    -                               "xs/functions/index.md"
    -                               "xs/constants/index.md"
    - Known Bugs:
      -                             "xs/bugs/index.md"
      # -                             "xs/bugs/Fixed.md"
      -                             "xs/bugs/Important.md"
      -                             "xs/bugs/LanguageSyntax.md"
      -                             "xs/bugs/Crashes.md"
      -                             "xs/bugs/Editor.md"
      -                             "xs/bugs/ChatData.md"
      -                             "xs/bugs/EffectAmount.md"
  - Mods:
    -                               "mods/index.md"
#   - Data Mods
#     - Advanced Genie Editor:
#       - A.G.E. Basics:            "mods/age/basics.md"
#   - RMS:
#     - RMS Basics:                 "rms/basics.md"

markdown_extensions:
  - attr_list
  - admonition                # Create not and warning boxes        https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition
  - md_in_html
  - pymdownx.caret            # Handling sub- and superscripts      https://facelessuser.github.io/pymdown-extensions/extensions/caret/
  - pymdownx.critic           #                                     https://facelessuser.github.io/pymdown-extensions/extensions/critic/
  - pymdownx.details          # Collapsable elements                https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - pymdownx.inlinehilite     # Inline code highlighting            https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/
  - pymdownx.mark             # Highlighting of text                https://facelessuser.github.io/pymdown-extensions/extensions/mark/
  - pymdownx.smartsymbols     # Creating special characters         https://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/
  - pymdownx.snippets         #                                     https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
  - pymdownx.superfences
  - pymdownx.tabbed           # Tabs                                https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
  - pymdownx.tasklist         #                                     https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/
  - pymdownx.tilde            # Strikethrough of text               https://facelessuser.github.io/pymdown-extensions/extensions/tilde/
  - pymdownx.arithmatex:      # Preserve LaTeX math equations       https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/
      generic: true
  - pymdownx.emoji:           # Emojis                              https://facelessuser.github.io/pymdown-extensions/extensions/emoji/
      emoji_index:     !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:       # Highlighting code blocks            https://facelessuser.github.io/pymdown-extensions/extensions/highlight/
      linenums:     true
      use_pygments: true
  - pymdownx.keys:            # Add styling keyboard keys           https://facelessuser.github.io/pymdown-extensions/extensions/keys/
     strict: false
  - pymdownx.superfences:     # Complicated code fences             https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
      custom_fences:
        - name:   mermaid
          class:  mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:        # Creating Check-able tasklist        https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/
      custom_checkbox:    true
      clickable_checkbox: true
  - toc:
      permalink: true

plugins:
  - search:
      separator: '[\s\u200b\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

  - exclude:
      glob:
        - "*.json"
        - "*.py"

  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "en"]

      #This boolean (true/false) option is used to speed up the build process
      #while developing your documentation.
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]

      docs_structure: suffix
      languages:
        en:
          name: English
          build: false
        zh:
          name: 简体中文(Chinese, Simplified)
          site_name: AoE2DE UGC 手册
      nav_translations:
        zh:
          Game Mechanics: 游戏机制
          Custom Scenarios: 自定义场景
          XS Scripting: XS 脚本语言
          Mods: 模组

          Damage Calculation: 伤害计算

          Triggers: 触发
          Effects: 效果
          Conditions: 条件
          Variables: 变量
          Tricks and Tips: 技巧与提示
          Advanced: 高级
          File Byte Structure: 文件字节结构
          Useful Tools: 实用工具

          Advanced Genie Editor: AGE (高级数据编辑器)
          AoE2ScenarioParser: ASP (场景解析器)

          For Beginners: 对于初学者

          For Programmers: 对于程序员
          Tricks: 技巧
          Functions Reference: 函数参考
          Constant Reference: 常量参考
          Known Bugs: 已知 Bugs

theme:
  # favicon: assets/images/favicon.png
  name: material
  features:
    - content.code.annotate
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    - toc.follow
  font:
    text: Roboto
    code: Fira Code
  icon:
    logo: octicons/file-code-24
    admonition:
      abstract: octicons/checklist-16
      bug:      octicons/bug-16
      danger:   octicons/zap-16
      example:  octicons/beaker-16
      failure:  octicons/x-circle-16
      info:     octicons/info-16
      note:     octicons/tag-16
      success:  octicons/check-16
      tip:      octicons/squirrel-16
      question: octicons/question-16
      quote:    octicons/quote-16
      warning:  octicons/alert-16
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: light blue
      accent:  light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent:  red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  # - ./assets/javascripts/lang-select.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - ./assets/stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-X6E7LFHRLR
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
