Invoke-Expression $PSScriptRoot"./gen_attrs.ps1"
Invoke-Expression $PSScriptRoot"./gen_res.ps1"
Invoke-Expression $PSScriptRoot"./gen_xs_const.ps1"
Invoke-Expression $PSScriptRoot"./gen_xs_func.ps1"
# Invoke-Expression $PSScriptRoot"./gen_xs_bugs.ps1"
